# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dockerpassword
      MYSQL_DATABASE: GameGeekt_Database
      MYSQL_USER: admin
      MYSQL_PASSWORD: gamegeekt
    ports:
      - "3306:3306"
    networks:
      - app-network
  redis:
    image: redis
    volumes:
      - redis:/var/lib/redis
    ports:
      - "6379:6379"
    networks:
      - app-network
  # server:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: server
  #   container_name: server
  #   restart: unless-stopped
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - .:/app
  #     - node_modules:/node_modules
  #   environment:
  #     dbhost: db
  #     dbport: 3306
  #     dbusername: admin
  #     dbpassword: gamegeekt
  #     dbname: GameGeekt_Database
  #     redishost: redis
  #     origin: http://localhost:3000
  #   command: node app.js
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: {} 
  redis:
  node_modules: